=== KacperKafara/LandlordKingdom/src/test/resources/datasets/molSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dataset">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="addresses" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="locals" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="rents" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="applications" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="locals">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="description" type="xs:string" use="required"/>
            <xs:attribute name="size" type="xs:integer" use="required"/>
            <xs:attribute name="state" type="xs:integer" use="required"/>
            <xs:attribute name="address_id" type="xs:string" use="required"/>
            <xs:attribute name="owner_id" type="xs:string" use="optional"/>
            <xs:attribute name="margin_fee" type="xs:integer" use="required"/>
            <xs:attribute name="next_margin_fee" type="xs:integer" use="optional"/>
            <xs:attribute name="rental_fee" type="xs:integer" use="required"/>
            <xs:attribute name="next_rental_fee" type="xs:integer" use="optional"/>
            <xs:attribute name="version" type="xs:integer" use="required"/>
            <xs:attribute name="created_at" type="xs:string" use="required"/>
            <xs:attribute name="modified_at" type="xs:string" use="required"/>
            <xs:attribute name="created_by" type="xs:string" use="optional"/>
            <xs:attribute name="modified_by" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="addresses">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="number" type="xs:string" use="required"/>
            <xs:attribute name="street" type="xs:string" use="required"/>
            <xs:attribute name="city" type="xs:string" use="required"/>
            <xs:attribute name="zip" type="xs:string" use="required"/>
            <xs:attribute name="country" type="xs:string" use="required"/>
            <xs:attribute name="version" type="xs:integer" use="required"/>
            <xs:attribute name="created_at" type="xs:string" use="required"/>
            <xs:attribute name="modified_at" type="xs:string" use="required"/>
            <xs:attribute name="created_by" type="xs:string" use="optional"/>
            <xs:attribute name="modified_by" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="rents">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="local_id" type="xs:string" use="required"/>
            <xs:attribute name="tenant_id" type="xs:string" use="required"/>
            <xs:attribute name="owner_id" type="xs:string" use="required"/>
            <xs:attribute name="start_date" type="xs:string" use="required"/>
            <xs:attribute name="end_date" type="xs:string" use="required"/>
            <xs:attribute name="balance" type="xs:integer" use="required"/>
            <xs:attribute name="version" type="xs:integer" use="required"/>
            <xs:attribute name="created_at" type="xs:string" use="required"/>
            <xs:attribute name="modified_at" type="xs:string" use="required"/>
            <xs:attribute name="created_by" type="xs:string" use="optional"/>
            <xs:attribute name="modified_by" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
    '
    <xs:element name="applications">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="created_at" type="xs:string" use="required"/>
            <xs:attribute name="modified_at" type="xs:string" use="required"/>
            <xs:attribute name="created_by" type="xs:string" use="optional"/>
            <xs:attribute name="modified_by" type="xs:string" use="optional"/>
            <xs:attribute name="version" type="xs:integer" use="required"/>
            <xs:attribute name="local_id" type="xs:string" use="required"/>
            <xs:attribute name="tenant_id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== KacperKafara/LandlordKingdom/src/test/resources/datasets/molDataForLocalControllerIT.xml
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="molSchema.xsd">

    <addresses id="1ae4ec9b-286d-4506-b915-b5b9527284e0"
               number="1"
               street="localWithoutOwnerStreet"
               city="localWithoutOwnerCity"
               zip="123-12"
               country="localWithoutOwnerCountry"
               version="0"
               created_at="2024-05-04 14:33:01.413581"
               modified_at="2024-05-04 14:33:01.413581"
               created_by="[NULL]"
               modified_by="[NULL]"/>
    
    <locals id="64d715a3-0dd5-4520-9716-965db9ce1ac5"
            name="localWithoutOwner"
            description="localWithoutOwner"
            size="2"
            state="4"
            address_id="1ae4ec9b-286d-4506-b915-b5b9527284e0"
            margin_fee="50"
            rental_fee="50"
            version="1"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            created_by="[NULL]"
            modified_by="[NULL]"/>

    <addresses id="1ae4ec9b-286d-4506-b915-b5b9527284e9"
               number="1"
               street="inactiveLocalStreet"
               city="inactiveLocalCity"
               zip="12-312"
               country="inactiveLocalCountry"
               version="0"
               created_at="2024-05-04 14:33:01.413581"
               modified_at="2024-05-04 14:33:01.413581"
               created_by="[NULL]"
               modified_by="[NULL]"/>

    <locals id="64d715a3-0dd5-4520-9716-965db9ce1ac6"
            name="local"
            description="inactiveLocal"
            size="2"
            state="3"
            address_id="1ae4ec9b-286d-4506-b915-b5b9527284e9"
            margin_fee="50"
            rental_fee="50"
            version="1"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            created_by="[NULL]"
            modified_by="[NULL]"/>
    
    <addresses id="065cee24-bbc4-4b45-89c9-48852207d14c"
               number="1"
               street="archivedLocalStreet"
               city="archivedLocalCity"
               zip="12-123"
               country="archivedLocalCountry" 
               version="1"
               created_at="2024-05-04 14:33:01.413581"
               modified_at="2024-05-04 14:33:01.413581" />
    
    <locals id="ff345812-b51c-4518-9c3f-8b0742392170"
            name="archivedLocal"
            description="archivedLocal"
            size="2"
            state="1"
            address_id="065cee24-bbc4-4b45-89c9-48852207d14c"
            margin_fee="10"
            rental_fee="14"
            version="1"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581" />

    <addresses id="ce8bb9fb-e7dd-4516-91d1-ef7ab09b9e57"
               number="1"
               street="unapprovedLocalStreet"
               city="unapprovedLocalCity"
               zip="12-123"
               country="unapprovedLocalCountry"
               version="1"
               created_at="2024-05-04 14:33:01.413581"
               modified_at="2024-05-04 14:33:01.413581" />

    <locals id="ec15320f-1dfc-495b-b2cf-2964c0b7ccd9"
            name="unapprovedLocal"
            description="unapprovedLocal"
            size="2"
            state="0"
            address_id="ce8bb9fb-e7dd-4516-91d1-ef7ab09b9e57"
            margin_fee="10"
            rental_fee="14"
            version="1"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581" />
</dataset>

=== KacperKafara/LandlordKingdom/src/test/resources/datasets/molDataForApplicationControllerIT.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="molSchema.xsd">

    <!-- address1 -->
    <addresses id="1ae4ec9b-286d-4506-b915-b5b9527284e0"
               number="1"
               street="inactiveLocalStreet"
               city="inactiveLocalCity"
               zip="123-12"
               country="inactiveLocalCountry"
               version="0"
               created_at="2024-05-04 14:33:01.413581"
               modified_at="2024-05-04 14:33:01.413581"
               created_by="[NULL]"
               modified_by="[NULL]"/>

    <!-- address2 -->
    <addresses id="947ce115-d492-4508-b432-8a5711bad5d4"
               number="1"
               street="rentedLocalStreet"
               city="rentedLocalCity"
               zip="123-12"
               country="rentedLocalCountry"
               version="0"
               created_at="2024-05-04 14:33:01.413581"
               modified_at="2024-05-04 14:33:01.413581"
               created_by="[NULL]"
               modified_by="[NULL]"/>

    <!-- address3 -->
    <addresses id="a7717971-96e7-4dfc-b149-c1552b858f34"
               number="1"
               street="aleadres"
               city="afterRentLocalCity"
               zip="123-12"
               country="afterRentLocalCountry"
               version="0"
               created_at="2024-05-04 14:33:01.413581"
               modified_at="2024-05-04 14:33:01.413581"
               created_by="[NULL]"
               modified_by="[NULL]"/>

    <!-- active local 1 -->
    <locals id="7436607c-5928-489e-adba-511541df1b8d"
            name="activeLocal1"
            description="description1"
            size="100"
            state="2"
            address_id="a7717971-96e7-4dfc-b149-c1552b858f34"
            owner_id="d1130c9a-3bbb-4927-b79f-0fd521fa55ea"
            margin_fee="100"
            rental_fee="1000"
            version="0"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            created_by="[NULL]"
            modified_by="[NULL]"/>

    <!-- address3 -->
    <addresses id="5a5f9400-9340-42e6-9914-a97ca03409d9"
               number="1"
               street="afterRentLocalStreet"
               city="afterRentLocalCity"
               zip="123-12"
               country="afterRentLocalCountry"
               version="0"
               created_at="2024-05-04 14:33:01.413581"
               modified_at="2024-05-04 14:33:01.413581"
               created_by="[NULL]"
               modified_by="[NULL]"/>

    <!-- active local 1 -->
    <locals id="3db8f4a7-a268-41a8-84f8-5e1a1dc4b4d0"
            name="activeLocal1"
            description="description1"
            size="100"
            state="2"
            address_id="1ae4ec9b-286d-4506-b915-b5b9527284e0"
            owner_id="d1130c9a-3bbb-4927-b79f-0fd521fa55ea"
            margin_fee="100"
            rental_fee="1000"
            version="0"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            created_by="[NULL]"
            modified_by="[NULL]"/>

    <!-- active local 2 -->
    <locals id="a51f1e3e-e0e6-4a7d-80e5-16e245554c77"
            name="activeLocal2"
            description="description2"
            size="100"
            state="2"
            address_id="947ce115-d492-4508-b432-8a5711bad5d4"
            owner_id="d1130c9a-3bbb-4927-b79f-0fd521fa55ea"
            margin_fee="100"
            rental_fee="1000"
            version="0"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            created_by="[NULL]"
            modified_by="[NULL]"/>

    <!-- inactive local 1 -->
    <locals id="222a7a48-3370-4fde-93b7-b3191671cdb3"
            name="inactive1"
            description="description3"
            size="100"
            state="3"
            address_id="5a5f9400-9340-42e6-9914-a97ca03409d9"
            owner_id="d1130c9a-3bbb-4927-b79f-0fd521fa55ea"
            margin_fee="100"
            rental_fee="1000"
            version="0"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            created_by="[NULL]"
            modified_by="[NULL]"/>

    <!-- application for local active 2 and tenantMeTenant -->
    <applications id="6bc94516-c901-4ac1-8627-bffe4232c0d3" created_at="2024-05-04 14:33:01.413581"
                  modified_at="2024-05-04 14:33:01.413581"
                  version="1"
                  local_id="a51f1e3e-e0e6-4a7d-80e5-16e245554c77"
                  tenant_id="23aeee47-6b75-4de3-8313-5fccd3de841f"/>

</dataset>

=== KacperKafara/LandlordKingdom/src/test/resources/datasets/molDataForMeTenantControllerIT.xml
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="molSchema.xsd">


    <addresses id="1ae4ec9b-286d-4506-b915-b5b9527284e0"
               number="1"
               street="inactiveLocalStreet"
               city="inactiveLocalCity"
               zip="123-12"
               country="inactiveLocalCountry"
               version="0"
               created_at="2024-05-04 14:33:01.413581"
               modified_at="2024-05-04 14:33:01.413581"
               created_by="[NULL]"
               modified_by="[NULL]"/>

    <addresses id="947ce115-d492-4508-b432-8a5711bad5d4"
               number="1"
               street="rentedLocalStreet"
               city="rentedLocalCity"
               zip="123-12"
               country="rentedLocalCountry"
               version="0"
               created_at="2024-05-04 14:33:01.413581"
               modified_at="2024-05-04 14:33:01.413581"
               created_by="[NULL]"
               modified_by="[NULL]"/>

    <addresses id="5a5f9400-9340-42e6-9914-a97ca03409d9"
               number="1"
               street="afterRentLocalStreet"
               city="afterRentLocalCity"
               zip="123-12"
               country="afterRentLocalCountry"
               version="0"
               created_at="2024-05-04 14:33:01.413581"
               modified_at="2024-05-04 14:33:01.413581"
               created_by="[NULL]"
               modified_by="[NULL]"/>

    <addresses id="47c6513b-9619-4430-979f-978f165481db"
               number="12"
               street="afterRentLocalStreet1"
               city="afterRentLocalCit1y"
               zip="123-13"
               country="afterRentLocalCountry1"
               version="0"
               created_at="2024-05-04 14:33:01.413581"
               modified_at="2024-05-04 14:33:01.413581"
               created_by="[NULL]"
               modified_by="[NULL]"/>


    <locals id="3db8f4a7-a268-41a8-84f8-5e1a1dc4b4d0"
            name="inactiveLocal"
            description="mol8local description"
            size="100"
            state="3"
            address_id="1ae4ec9b-286d-4506-b915-b5b9527284e0"
            owner_id="d1130c9a-3bbb-4927-b79f-0fd521fa55ea"
            margin_fee="100"
            rental_fee="1000"
            version="0"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            created_by="[NULL]"
            modified_by="[NULL]"/>

    <locals id="a51f1e3e-e0e6-4a7d-80e5-16e245554c77"
            name="rentedLocal"
            description="mol8local description"
            size="100"
            state="5"
            address_id="947ce115-d492-4508-b432-8a5711bad5d4"
            owner_id="d1130c9a-3bbb-4927-b79f-0fd521fa55ea"
            margin_fee="100"
            rental_fee="1000"
            version="0"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            created_by="[NULL]"
            modified_by="[NULL]"/>

    <locals id="222a7a48-3370-4fde-93b7-b3191671cdb3"
            name="inactiveLocalAfterRent"
            description="mol8local description"
            size="100"
            state="3"
            address_id="5a5f9400-9340-42e6-9914-a97ca03409d9"
            owner_id="d1130c9a-3bbb-4927-b79f-0fd521fa55ea"
            margin_fee="100"
            rental_fee="1000"
            version="0"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            created_by="[NULL]"
            modified_by="[NULL]"/>

    <locals id="47c6513b-9619-4430-979f-978f165481db"
            name="inactiveLocalAfterRent"
            description="mol8local description"
            size="100"
            state="3"
            address_id="5a5f9400-9340-42e6-9914-a97ca03409d9"
            owner_id="d1130c9a-3bbb-4927-b79f-0fd521fa55ea"
            margin_fee="100"
            rental_fee="1000"
            version="0"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            created_by="[NULL]"
            modified_by="[NULL]"/>

    <rents id="31658859-f2dc-425a-bb98-8f444960bb35"
           balance="1000"
           local_id="222a7a48-3370-4fde-93b7-b3191671cdb3"
           owner_id="d1130c9a-3bbb-4927-b79f-0fd521fa55ea"
           tenant_id="673a4bf2-e274-4185-89c6-f67891a3cbe0"
           version="0"
           start_date="2024-01-20"
           end_date="2024-05-05"
           created_at="2024-05-04 14:33:01.413581"
           modified_at="2024-05-04 14:33:01.413581"
           created_by="[NULL]"
           modified_by="[NULL]"/>


    <rents id="5571842e-ec61-4a03-8715-36ccf3c5aa35"
           balance="1000"
           local_id="a51f1e3e-e0e6-4a7d-80e5-16e245554c77"
           owner_id="d1130c9a-3bbb-4927-b79f-0fd521fa55ea"
           tenant_id="673a4bf2-e274-4185-89c6-f67891a3cbe0"
           version="0"
           start_date="2024-01-20"
           end_date="2024-09-01"
           created_at="2024-05-04 14:33:01.413581"
           modified_at="2024-05-04 14:33:01.413581"
           created_by="[NULL]"
           modified_by="[NULL]"/>

    <rents id="2fde7510-8d4c-49cd-aa1d-5d848b510e23"
           balance="1000"
           local_id="47c6513b-9619-4430-979f-978f165481db"
           owner_id="d1130c9a-3bbb-4927-b79f-0fd521fa55ea"
           tenant_id="673a4bf2-e274-4185-89c6-f67891a3cbe0"
           version="0"
           start_date="2024-01-20"
           end_date="2024-09-01"
           created_at="2024-05-04 14:33:01.413581"
           modified_at="2024-05-04 14:33:01.413581"
           created_by="[NULL]"
           modified_by="[NULL]"/>
</dataset>
