=== KacperKafara/LandlordKingdom/src/test/resources/datasets/userSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Define element types -->
    <xs:element name="dataset">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="users" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="personal_data" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="access_levels" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="administrators" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="owners" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="tenants" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="users">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="login" type="xs:string" use="required"/>
            <xs:attribute name="password" type="xs:string" use="required"/>
            <xs:attribute name="login_attempts" type="xs:string" use="required"/>
            <xs:attribute name="last_successful_login" type="xs:string" use="optional"/>
            <xs:attribute name="last_failed_login" type="xs:string" use="optional"/>
            <xs:attribute name="last_successful_login_ip" type="xs:string" use="optional"/>
            <xs:attribute name="last_failed_login_ip" type="xs:string" use="optional"/>
            <xs:attribute name="blocked" type="xs:boolean" use="required"/>
            <xs:attribute name="verified" type="xs:boolean" use="required"/>
            <xs:attribute name="language" type="xs:string" use="required"/>
            <xs:attribute name="version" type="xs:string" use="required"/>
            <xs:attribute name="created_at" type="xs:string" use="required"/>
            <xs:attribute name="modified_at" type="xs:string" use="required"/>
            <xs:attribute name="created_by" type="xs:string" use="optional"/>
            <xs:attribute name="modified_by" type="xs:string" use="optional"/>
            <xs:attribute name="active" type="xs:boolean" use="required"/>
            <xs:attribute name="theme" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="personal_data">
        <xs:complexType>
            <xs:attribute name="user_id" type="xs:string" use="required"/>
            <xs:attribute name="email" type="xs:string" use="required"/>
            <xs:attribute name="first_name" type="xs:string" use="required"/>
            <xs:attribute name="last_name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="access_levels">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="user_id" type="xs:string" use="required"/>
            <xs:attribute name="level" type="xs:string" use="required"/>
            <xs:attribute name="active" type="xs:boolean" use="required"/>
            <xs:attribute name="version" type="xs:string" use="required"/>
            <xs:attribute name="created_at" type="xs:string" use="required"/>
            <xs:attribute name="modified_at" type="xs:string" use="required"/>
            <xs:attribute name="created_by" type="xs:string" use="optional"/>
            <xs:attribute name="modified_by" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="administrators">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="owners">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="tenants">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== KacperKafara/LandlordKingdom/src/test/resources/datasets/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="userSchema.xsd">
    <!-- Users data -->
    <users id="ba537227-d54f-42b3-aa58-10492cddf8a6"
           login="test_login1"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           last_successful_login="2024-05-04 14:33:01.413581"
           last_failed_login="2024-05-04 14:33:01.413581"
           last_successful_login_ip="[NULL]"
           last_failed_login_ip="[NULL]"
           blocked="false"
           verified="true"
           language="EN"
           version="0"
           created_at="2024-05-04 14:33:01.413581"
           modified_at="2024-05-04 14:33:01.413581"
           created_by="[NULL]"
           modified_by="[NULL]"/>


    <!-- Personal Data -->
    <personal_data user_id="ba537227-d54f-42b3-aa58-10492cddf8a6"
                   email="test_email1@test.com"
                   first_name="test_first_name1"
                   last_name="test_last_name1"/>

    <!-- User 1 -->
    <access_levels active="true"
                   version="0"
                   id="22f34716-3b77-4e63-809d-35f9a4758011"
                   user_id="ba537227-d54f-42b3-aa58-10492cddf8a6"
                   level="TENANT"
                   created_at="2024-05-04 14:33:01.413581"
                   modified_at="2024-05-04 14:33:01.413581"
                   created_by="[NULL]"
                   modified_by="[NULL]"/>
    <access_levels active="true"
                   version="0"
                   id="397cf3c5-f369-4783-1092-6fc781fd2b0d"
                   user_id="ba537227-d54f-42b3-aa58-10492cddf8a6"
                   level="OWNER"
                   created_at="2024-05-04 14:33:01.413581"
                   modified_at="2024-05-04 14:33:01.413581"
                   created_by="[NULL]"
                   modified_by="[NULL]"/>
    <access_levels active="true"
                   version="0"
                   id="6bcef94d-16f5-401b-a0d0-9461257572f6"
                   user_id="ba537227-d54f-42b3-aa58-10492cddf8a6"
                   level="ADMINISTRATOR"
                   created_at="2024-05-04 14:33:01.413581"
                   modified_at="2024-05-04 14:33:01.413581"
                   created_by="[NULL]"
                   modified_by="[NULL]"/>


    <!-- Administrators -->
    <administrators id="6bcef94d-16f5-401b-a0d0-9461257572f6"/>

    <!-- Owners -->
    <owners id="397cf3c5-f369-4783-1092-6fc781fd2b0d"/>

    <!-- Tenants -->
    <tenants id="22f34716-3b77-4e63-809d-35f9a4758011"/>
</dataset>

=== KacperKafara/LandlordKingdom/src/test/resources/datasets/userDataForMeOwnerIT.xml
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="userSchema.xsd">

    <users id="1ae4ec9b-286d-4506-b915-b5b9527284e0"
           login="mol8owner"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           last_successful_login="2024-05-04 14:33:01.413581"
           last_failed_login="2024-05-04 14:33:01.413581"
           last_successful_login_ip="[NULL]"
           last_failed_login_ip="[NULL]"
           blocked="false"
           verified="true"
           language="EN"
           version="0"
           created_at="2024-05-04 14:33:01.413581"
           modified_at="2024-05-04 14:33:01.413581"
           created_by="[NULL]"
           modified_by="[NULL]"
           active="true"/>

    <users id="7a5ea9fe-8cbc-4ccb-b9f7-243316bf0390"
           login="mol8tenant"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           last_successful_login="2024-05-04 14:33:01.413581"
           last_failed_login="2024-05-04 14:33:01.413581"
           last_successful_login_ip="[NULL]"
           last_failed_login_ip="[NULL]"
           blocked="false"
           verified="true"
           language="EN"
           version="0"
           created_at="2024-05-04 14:33:01.413581"
           modified_at="2024-05-04 14:33:01.413581"
           created_by="[NULL]"
           modified_by="[NULL]"
           active="true"/>

    <users id="841da5ec-a0a7-46b3-a568-d8052f5fddba"
           login="mol8admin"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           last_successful_login="2024-05-04 14:33:01.413581"
           last_failed_login="2024-05-04 14:33:01.413581"
           last_successful_login_ip="[NULL]"
           last_failed_login_ip="[NULL]"
           blocked="false"
           verified="true"
           language="EN"
           version="0"
           created_at="2024-05-04 14:33:01.413581"
           modified_at="2024-05-04 14:33:01.413581"
           created_by="[NULL]"
           modified_by="[NULL]"
           active="true"/>

    <!-- Token -->
    <tokens id="063612b8-57e2-4a73-bf8e-6cd7cc7c3b4a"
            token="20099995"
            purpose="OTP"
            user_id="1ae4ec9b-286d-4506-b915-b5b9527284e0"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            expiration_date="2039-05-04 14:33:01.413581"
            version="0"
            created_by="[NULL]"
            modified_by="[NULL]"/>

    <tokens id="0a4f4be4-3123-4a72-8152-0b2a7d5e0e5c"
            token="20099997"
            purpose="OTP"
            user_id="841da5ec-a0a7-46b3-a568-d8052f5fddba"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            expiration_date="2039-05-04 14:33:01.413581"
            version="0"
            created_by="[NULL]"
            modified_by="[NULL]"/>

    <tokens id="422070b8-8e14-4cf4-8d58-9a01ea38738f"
            token="30099997"
            purpose="OTP"
            user_id="7a5ea9fe-8cbc-4ccb-b9f7-243316bf0390"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            expiration_date="2039-05-04 14:33:01.413581"
            version="0"
            created_by="[NULL]"
            modified_by="[NULL]"/>

    <!-- Personal Data -->
    <personal_data user_id="1ae4ec9b-286d-4506-b915-b5b9527284e0"
                   email="mol8user@test.com"
                   temp_email="[NULL]"
                   first_name="test_first_name1"
                   last_name="test_last_name1"/>

    <personal_data user_id="841da5ec-a0a7-46b3-a568-d8052f5fddba"
                   email="mol8admin@test.com"
                   temp_email="[NULL]"
                   first_name="test_first_name1"
                   last_name="test_last_name1"/>

    <personal_data user_id="7a5ea9fe-8cbc-4ccb-b9f7-243316bf0390"
                   email="mol8tenant@test.com"
                   temp_email="[NULL]"
                   first_name="test_first_name1"
                   last_name="test_last_name1"/>

    <!-- User 1 -->
    <access_levels active="true"
                   version="0"
                   id="d1130c9a-3bbb-4927-b79f-0fd521fa55ea"
                   user_id="1ae4ec9b-286d-4506-b915-b5b9527284e0"
                   level="OWNER"
                   created_at="2024-05-04 14:33:01.413581"
                   modified_at="2024-05-04 14:33:01.413581"
                   created_by="[NULL]"
                   modified_by="[NULL]"/>

    <access_levels active="true"
                   version="0"
                   id="8804724c-7cc3-4ec1-aad6-dd11c5f507ba"
                   user_id="841da5ec-a0a7-46b3-a568-d8052f5fddba"
                   level="ADMINISTRATOR"
                   created_at="2024-05-04 14:33:01.413581"
                   modified_at="2024-05-04 14:33:01.413581"
                   created_by="[NULL]"
                   modified_by="[NULL]"/>

    <access_levels active="true"
                   version="0"
                   id="23aeee47-6b75-4de3-8313-5fccd3de841f"
                   user_id="7a5ea9fe-8cbc-4ccb-b9f7-243316bf0390"
                   level="TENANT"
                   created_at="2024-05-04 14:33:01.413581"
                   modified_at="2024-05-04 14:33:01.413581"
                   created_by="[NULL]"
                   modified_by="[NULL]"/>

    <owners id="d1130c9a-3bbb-4927-b79f-0fd521fa55ea"/>
    <administrators id="8804724c-7cc3-4ec1-aad6-dd11c5f507ba"/>
    <tenants id="23aeee47-6b75-4de3-8313-5fccd3de841f"/>
</dataset>

=== KacperKafara/LandlordKingdom/src/test/resources/datasets/UsersForAdministratorsIT.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="userSchema.xsd">
    <!-- Administrator -->
    <users id="ba537227-d54f-42b3-aa58-10492cddf8a5"
           login="adminUser"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           last_successful_login="2024-05-04 14:33:01.413581"
           last_failed_login="2024-05-04 14:33:01.413581"
           last_successful_login_ip="[NULL]"
           last_failed_login_ip="[NULL]"
           blocked="false"
           verified="true"
           language="EN"
           version="0"
           created_at="[NOW]"
           modified_at="[NOW]"
           created_by="[NULL]"
           modified_by="[NULL]"
           active="true"
           theme="LIGHT"/>

    <!-- Personal Data -->
    <personal_data user_id="ba537227-d54f-42b3-aa58-10492cddf8a5"
                   email="adminUser@test.com"
                   temp_email="[NULL]"
                   first_name="AdminUser"
                   last_name="AdminUser"/>

    <!-- Access Level -->
    <access_levels active="true"
                   version="0"
                   id="22f34716-3b77-4e63-809d-35f9a4758011"
                   user_id="ba537227-d54f-42b3-aa58-10492cddf8a5"
                   level="ADMINISTRATOR"
                   created_at="[NOW]"
                   modified_at="[NOW]"
                   created_by="[NULL]"
                   modified_by="[NULL]"/>

    <!-- Administrator -->
    <administrators id="22f34716-3b77-4e63-809d-35f9a4758011"/>

    <!-- User -->
    <users id="ba537227-d54f-42b3-aa58-10492cddf8a6"
           login="adimnUser2"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           last_successful_login="2024-05-04 14:33:01.413581"
           last_failed_login="2024-05-04 14:33:01.413581"
           last_successful_login_ip="[NULL]"
           last_failed_login_ip="[NULL]"
           blocked="false"
           verified="true"
           language="EN"
           version="0"
           created_at="[NOW]"
           modified_at="[NOW]"
           created_by="[NULL]"
           modified_by="[NULL]"
           active="true"
           theme="LIGHT"/>

    <!-- Personal Data -->
    <personal_data user_id="ba537227-d54f-42b3-aa58-10492cddf8a6"
                   email="adimnUser2@test.com"
                   temp_email="[NULL]"
                   first_name="User"
                   last_name="Owner"/>

    <!-- Access Level -->
    <access_levels active="true"
                   version="0"
                   id="22f34716-3b77-4e63-809d-35f9a4758012"
                   user_id="ba537227-d54f-42b3-aa58-10492cddf8a6"
                   level="ADMINISTRATOR"
                   created_at="[NOW]"
                   modified_at="[NOW]"
                   created_by="[NULL]"
                   modified_by="[NULL]"/>

    <!-- Tenant -->
    <administrators id="22f34716-3b77-4e63-809d-35f9a4758012"/>

    <!-- User -->
    <users id="ba537227-d54f-42b3-aa58-10492cddf8a7"
           login="user"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           last_successful_login="2024-05-04 14:33:01.413581"
           last_failed_login="2024-05-04 14:33:01.413581"
           last_successful_login_ip="[NULL]"
           last_failed_login_ip="[NULL]"
           blocked="false"
           verified="true"
           language="EN"
           version="0"
           created_at="[NOW]"
           modified_at="[NOW]"
           created_by="[NULL]"
           modified_by="[NULL]"
           active="true"
           theme="LIGHT"/>

    <!-- Personal Data -->
    <personal_data user_id="ba537227-d54f-42b3-aa58-10492cddf8a7"
                   email="user@test.com"
                   temp_email="[NULL]"
                   first_name="User"
                   last_name="User"/>
</dataset>

=== KacperKafara/LandlordKingdom/src/test/resources/datasets/mokDataForApplicationControllerIT.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="userSchema.xsd">

    <users id="1ae4ec9b-286d-4506-b915-b5b9527284e0"
           login="testOwner"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           last_successful_login="2024-05-04 14:33:01.413581"
           last_failed_login="2024-05-04 14:33:01.413581"
           last_successful_login_ip="[NULL]"
           last_failed_login_ip="[NULL]"
           blocked="false"
           verified="true"
           language="EN"
           version="0"
           created_at="2024-05-04 14:33:01.413581"
           modified_at="2024-05-04 14:33:01.413581"
           created_by="[NULL]"
           modified_by="[NULL]"
           active="true"/>

    <users id="5af27f1c-5460-456f-877a-e73bc345e0b6"
           login="testOwner2"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           last_successful_login="2024-05-04 14:33:01.413581"
           last_failed_login="2024-05-04 14:33:01.413581"
           last_successful_login_ip="[NULL]"
           last_failed_login_ip="[NULL]"
           blocked="false"
           verified="true"
           language="EN"
           version="0"
           created_at="2024-05-04 14:33:01.413581"
           modified_at="2024-05-04 14:33:01.413581"
           created_by="[NULL]"
           modified_by="[NULL]"
           active="true"/>

    <users id="7a5ea9fe-8cbc-4ccb-b9f7-243316bf0390"
           login="testTenant"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           last_successful_login="2024-05-04 14:33:01.413581"
           last_failed_login="2024-05-04 14:33:01.413581"
           last_successful_login_ip="[NULL]"
           last_failed_login_ip="[NULL]"
           blocked="false"
           verified="true"
           language="EN"
           version="0"
           created_at="2024-05-04 14:33:01.413581"
           modified_at="2024-05-04 14:33:01.413581"
           created_by="[NULL]"
           modified_by="[NULL]"
           active="true"/>

    <!-- Token -->
    <tokens id="063612b8-57e2-4a73-bf8e-6cd7cc7c3b4a"
            token="20099995"
            purpose="OTP"
            user_id="1ae4ec9b-286d-4506-b915-b5b9527284e0"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            expiration_date="2039-05-04 14:33:01.413581"
            version="0"
            created_by="[NULL]"
            modified_by="[NULL]"/>

    <tokens id="8ff10b31-72a4-434d-a96f-e7d9a269732e"
            token="30099990"
            purpose="OTP"
            user_id="5af27f1c-5460-456f-877a-e73bc345e0b6"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            expiration_date="2039-05-04 14:33:01.413581"
            version="0"
            created_by="[NULL]"
            modified_by="[NULL]"/>

    <tokens id="422070b8-8e14-4cf4-8d58-9a01ea38738f"
            token="30099997"
            purpose="OTP"
            user_id="7a5ea9fe-8cbc-4ccb-b9f7-243316bf0390"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            expiration_date="2039-05-04 14:33:01.413581"
            version="0"
            created_by="[NULL]"
            modified_by="[NULL]"/>

    <!-- Personal Data -->
    <personal_data user_id="1ae4ec9b-286d-4506-b915-b5b9527284e0"
                   email="testOwner@test.com"
                   temp_email="[NULL]"
                   first_name="test_first_name1"
                   last_name="test_last_name1"/>

    <personal_data user_id="5af27f1c-5460-456f-877a-e73bc345e0b6"
                   email="testOwner2@test.com"
                   temp_email="[NULL]"
                   first_name="test_first_name1"
                   last_name="test_last_name1"/>

    <personal_data user_id="7a5ea9fe-8cbc-4ccb-b9f7-243316bf0390"
                   email="testTenant@test.com"
                   temp_email="[NULL]"
                   first_name="test_first_name1"
                   last_name="test_last_name1"/>

    <!-- User 1 -->
    <access_levels active="true"
                   version="0"
                   id="d1130c9a-3bbb-4927-b79f-0fd521fa55ea"
                   user_id="1ae4ec9b-286d-4506-b915-b5b9527284e0"
                   level="OWNER"
                   created_at="2024-05-04 14:33:01.413581"
                   modified_at="2024-05-04 14:33:01.413581"
                   created_by="[NULL]"
                   modified_by="[NULL]"/>

    <access_levels active="true"
                   version="0"
                   id="537838a6-441e-41ad-ab29-4c2f779729d5"
                   user_id="5af27f1c-5460-456f-877a-e73bc345e0b6"
                   level="OWNER"
                   created_at="2024-05-04 14:33:01.413581"
                   modified_at="2024-05-04 14:33:01.413581"
                   created_by="[NULL]"
                   modified_by="[NULL]"/>

    <access_levels active="true"
                   version="0"
                   id="23aeee47-6b75-4de3-8313-5fccd3de841f"
                   user_id="7a5ea9fe-8cbc-4ccb-b9f7-243316bf0390"
                   level="TENANT"
                   created_at="2024-05-04 14:33:01.413581"
                   modified_at="2024-05-04 14:33:01.413581"
                   created_by="[NULL]"
                   modified_by="[NULL]"/>

    <owners id="d1130c9a-3bbb-4927-b79f-0fd521fa55ea"/>
    <owners id="537838a6-441e-41ad-ab29-4c2f779729d5"/>
    <tenants id="23aeee47-6b75-4de3-8313-5fccd3de841f"/>

</dataset>

=== KacperKafara/LandlordKingdom/src/test/resources/datasets/usersForAdministratorsIT.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="userSchema.xsd">
    <!-- Administrator -->
    <users id="ba537227-d54f-42b3-aa58-10492cddf8a5"
           login="adminUser"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           blocked="false"
           verified="true"
           language="EN"
           version="0"
           created_at="[NOW]"
           modified_at="[NOW]"
           active="true"/>

    <!-- Token -->
    <tokens id="6bcef94d-16f5-401b-a0d0-9461257572f9"
            token="20099984"
            purpose="OTP"
            user_id="ba537227-d54f-42b3-aa58-10492cddf8a5"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            expiration_date="2039-05-04 14:33:01.413581"
            version="0"
            created_by="[NULL]"
            modified_by="[NULL]"/>

    <!-- Personal Data -->
    <personal_data user_id="ba537227-d54f-42b3-aa58-10492cddf8a5"
                   email="adminUser@test.com"
                   temp_email="[NULL]"
                   first_name="AdminUser"
                   last_name="AdminUser"/>

    <!-- Access Level -->
    <access_levels active="true"
                   version="0"
                   id="22f34716-3b77-4e63-809d-35f9a4758011"
                   user_id="ba537227-d54f-42b3-aa58-10492cddf8a5"
                   level="ADMINISTRATOR"
                   created_at="[NOW]"
                   modified_at="[NOW]"
                   created_by="[NULL]"
                   modified_by="[NULL]"/>

    <!-- Administrator -->
    <administrators id="22f34716-3b77-4e63-809d-35f9a4758011"/>

    <!-- User -->
    <users id="ba537227-d54f-42b3-aa58-10492cddf8a6"
           login="adimnUser2"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           blocked="false"
           verified="true"
           language="EN"
           version="0"
           created_at="[NOW]"
           modified_at="[NOW]"
           active="true"/>

    <!-- Personal Data -->
    <personal_data user_id="ba537227-d54f-42b3-aa58-10492cddf8a6"
                   email="adimnUser2@test.com"
                   temp_email="[NULL]"
                   first_name="User"
                   last_name="Owner"/>

    <!-- Access Level -->
    <access_levels active="true"
                   version="0"
                   id="22f34716-3b77-4e63-809d-35f9a4758012"
                   user_id="ba537227-d54f-42b3-aa58-10492cddf8a6"
                   level="ADMINISTRATOR"
                   created_at="[NOW]"
                   modified_at="[NOW]"
                   created_by="[NULL]"
                   modified_by="[NULL]"/>

    <!-- Administrator -->
    <administrators id="22f34716-3b77-4e63-809d-35f9a4758012"/>

    <!-- Access Level -->
    <access_levels active="true"
                   version="0"
                   id="22f34716-3b77-4e63-809d-35f9a4758013"
                   user_id="ba537227-d54f-42b3-aa58-10492cddf8a6"
                   level="TENANT"
                   created_at="[NOW]"
                   modified_at="[NOW]"
                   created_by="[NULL]"
                   modified_by="[NULL]"/>

    <!-- Tenant -->
    <tenants id="22f34716-3b77-4e63-809d-35f9a4758013"/>

    <!-- User -->
    <users id="ba537227-d54f-42b3-aa58-10492cddf8a7"
           login="user"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           blocked="false"
           verified="true"
           language="EN"
           version="0"
           created_at="[NOW]"
           modified_at="[NOW]"
           active="true"/>

    <!-- Personal Data -->
    <personal_data user_id="ba537227-d54f-42b3-aa58-10492cddf8a7"
                   email="user@test.com"
                   temp_email="[NULL]"
                   first_name="User"
                   last_name="User"/>
</dataset>
