=== KacperKafara/LandlordKingdom/src/test/resources/datasets/userSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Define element types -->
    <xs:element name="dataset">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="users" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="personal_data" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="access_levels" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="administrators" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="owners" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="tenants" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="users">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="login" type="xs:string" use="required"/>
            <xs:attribute name="password" type="xs:string" use="required"/>
            <xs:attribute name="login_attempts" type="xs:string" use="required"/>
            <xs:attribute name="last_successful_login" type="xs:string" use="optional"/>
            <xs:attribute name="last_failed_login" type="xs:string" use="optional"/>
            <xs:attribute name="last_successful_login_ip" type="xs:string" use="optional"/>
            <xs:attribute name="last_failed_login_ip" type="xs:string" use="optional"/>
            <xs:attribute name="blocked" type="xs:boolean" use="required"/>
            <xs:attribute name="verified" type="xs:boolean" use="required"/>
            <xs:attribute name="language" type="xs:string" use="required"/>
            <xs:attribute name="version" type="xs:string" use="required"/>
            <xs:attribute name="created_at" type="xs:string" use="required"/>
            <xs:attribute name="modified_at" type="xs:string" use="required"/>
            <xs:attribute name="created_by" type="xs:string" use="optional"/>
            <xs:attribute name="modified_by" type="xs:string" use="optional"/>
            <xs:attribute name="active" type="xs:boolean" use="required"/>
            <xs:attribute name="theme" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="personal_data">
        <xs:complexType>
            <xs:attribute name="user_id" type="xs:string" use="required"/>
            <xs:attribute name="email" type="xs:string" use="required"/>
            <xs:attribute name="first_name" type="xs:string" use="required"/>
            <xs:attribute name="last_name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="access_levels">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="user_id" type="xs:string" use="required"/>
            <xs:attribute name="level" type="xs:string" use="required"/>
            <xs:attribute name="active" type="xs:boolean" use="required"/>
            <xs:attribute name="version" type="xs:string" use="required"/>
            <xs:attribute name="created_at" type="xs:string" use="required"/>
            <xs:attribute name="modified_at" type="xs:string" use="required"/>
            <xs:attribute name="created_by" type="xs:string" use="optional"/>
            <xs:attribute name="modified_by" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="administrators">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="owners">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="tenants">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== KacperKafara/LandlordKingdom/src/test/resources/datasets/usersForAuthIT.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="userSchema.xsd">
    <!-- User data - Not Verified -->
    <users id="ba537227-d54f-42b3-aa58-10492cddf8a6"
           login="userNotVerified"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           last_successful_login="2024-05-04 14:33:01.413581"
           last_failed_login="2024-05-04 14:33:01.413581"
           last_successful_login_ip="[NULL]"
           last_failed_login_ip="[NULL]"
           blocked="false"
           verified="false"
           language="EN"
           version="0"
           created_at="[NOW]"
           modified_at="[NOW]"
           created_by="[NULL]"
           modified_by="[NULL]"
           active="true"
           theme="LIGHT"/>

    <!-- Personal Data -->
    <personal_data user_id="ba537227-d54f-42b3-aa58-10492cddf8a6"
                   email="userNotVerified@test.com"
                   first_name="test_first_name1"
                   last_name="test_last_name1"/>

    <!-- Access Level -->
    <access_levels active="true"
                   version="0"
                   id="22f34716-3b77-4e63-809d-35f9a4758011"
                   user_id="ba537227-d54f-42b3-aa58-10492cddf8a6"
                   level="TENANT"
                   created_at="[NOW]"
                   modified_at="[NOW]"
                   created_by="[NULL]"
                   modified_by="[NULL]"/>

    <!-- Tenant -->
    <tenants id="22f34716-3b77-4e63-809d-35f9a4758011"/>

    <!-- User data - Verified and Not Blocked -->
    <users id="2d1c91e8-cc0c-4f33-ae6e-20a9948a6f2d"
           login="userVerified"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           last_successful_login="2024-05-04 14:33:01.413581"
           last_failed_login="2024-05-04 14:33:01.413581"
           last_successful_login_ip="[NULL]"
           last_failed_login_ip="[NULL]"
           blocked="false"
           verified="true"
           language="EN"
           version="0"
           created_at="[NOW]"
           modified_at="[NOW]"
           created_by="[NULL]"
           modified_by="[NULL]"
           active="true"
           theme="LIGHT"/>

    <!-- Personal Data -->
    <personal_data user_id="2d1c91e8-cc0c-4f33-ae6e-20a9948a6f2d"
                   email="userVerified@test.com"
                   first_name="test_first_name2"
                   last_name="test_last_name2"/>

    <!-- Access Level -->
    <access_levels active="true"
                   version="0"
                   id="22f34716-3b77-4e63-809d-35f9a4758012"
                   user_id="2d1c91e8-cc0c-4f33-ae6e-20a9948a6f2d"
                   level="TENANT"
                   created_at="[NOW]"
                   modified_at="[NOW]"
                   created_by="[NULL]"
                   modified_by="[NULL]"/>

    <!-- Tenant -->
    <tenants id="22f34716-3b77-4e63-809d-35f9a4758012"/>

    <!-- User data - Blocked -->
    <users id="3a9a32e2-0f9e-4edf-b1ed-0e01386d6e49"
           login="userBlocked"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           last_successful_login="2024-05-04 14:33:01.413581"
           last_failed_login="2024-05-04 14:33:01.413581"
           last_successful_login_ip="[NULL]"
           last_failed_login_ip="[NULL]"
           blocked="true"
           verified="true"
           language="EN"
           version="0"
           created_at="[NOW]"
           modified_at="[NOW]"
           created_by="[NULL]"
           modified_by="[NULL]"
           active="true"
           theme="LIGHT"/>

    <!-- Personal Data -->
    <personal_data user_id="3a9a32e2-0f9e-4edf-b1ed-0e01386d6e49"
                   email="userBlocked@test.com"
                   first_name="test_first_name3"
                   last_name="test_last_name3"/>

    <!-- Access Level -->
    <access_levels active="true"
                   version="0"
                   id="22f34716-3b77-4e63-809d-35f9a4758013"
                   user_id="3a9a32e2-0f9e-4edf-b1ed-0e01386d6e49"
                   level="TENANT"
                   created_at="[NOW]"
                   modified_at="[NOW]"
                   created_by="[NULL]"
                   modified_by="[NULL]"/>

    <!-- Tenant -->
    <tenants id="22f34716-3b77-4e63-809d-35f9a4758013"/>

    <!-- User data - 3 Login Attempts (Last Failed Login 2 Days Ago) -->
    <users id="594d67c2-6820-4724-8f22-512dd097dc5e"
           login="userWithAttempts2DaysAgo"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="3"
           last_successful_login="2024-05-04 14:33:01.413581"
           last_failed_login="[now-2d]"
           last_successful_login_ip="[NULL]"
           last_failed_login_ip="[NULL]"
           blocked="false"
           verified="true"
           language="EN"
           version="0"
           created_at="[NOW]"
           modified_at="[NOW]"
           created_by="[NULL]"
           modified_by="[NULL]"
           active="true"
           theme="LIGHT"/>

    <!-- Personal Data -->
    <personal_data user_id="594d67c2-6820-4724-8f22-512dd097dc5e"
                   email="userWithAttempts2DaysAgo@test.com"
                   first_name="test_first_name5"
                   last_name="test_last_name5"/>

    <!-- Access Level -->
    <access_levels active="true"
                   version="0"
                   id="22f34716-3b77-4e63-809d-35f9a4758015"
                   user_id="594d67c2-6820-4724-8f22-512dd097dc5e"
                   level="TENANT"
                   created_at="[NOW]"
                   modified_at="[NOW]"
                   created_by="[NULL]"
                   modified_by="[NULL]"/>

    <!-- Tenant -->
    <tenants id="22f34716-3b77-4e63-809d-35f9a4758015"/>

</dataset>

=== KacperKafara/LandlordKingdom/src/test/resources/datasets/usersForRoleControllerIT.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="userSchema.xsd">

    <users id="093cdb69-4a4f-4932-a575-ffe76f40efce"
           login="testTenant"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           blocked="false"
           verified="true"
           language="EN"
           version="1"
           created_at="[NOW]"
           modified_at="[NOW]"
           active="true"/>

    <personal_data user_id="093cdb69-4a4f-4932-a575-ffe76f40efce"
                   email="testTenant@abcd.com"
                   first_name="test"
                   last_name="test"/>

    <access_levels active="true"
                   version="1"
                   id="9163ede4-241f-4b54-ab1a-d1eb6cc728d8"
                   user_id="093cdb69-4a4f-4932-a575-ffe76f40efce"
                   level="TENANT"
                   created_at="[NOW]"
                   modified_at="[NOW]"/>

    <tenants id="9163ede4-241f-4b54-ab1a-d1eb6cc728d8"/>

    <users id="b0194a97-9665-46e4-92bd-acf7538d4fa2"
           login="testTenantDwa"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           blocked="false"
           verified="true"
           language="EN"
           version="1"
           created_at="[NOW]"
           modified_at="[NOW]"
           active="true"/>

    <personal_data user_id="b0194a97-9665-46e4-92bd-acf7538d4fa2"
                   email="testTenantDwa@abcd.com"
                   first_name="test"
                   last_name="test"/>

    <access_levels active="true"
                   version="1"
                   id="201b7707-acc8-44d3-8275-4c3af41327eb"
                   user_id="b0194a97-9665-46e4-92bd-acf7538d4fa2"
                   level="TENANT"
                   created_at="[NOW]"
                   modified_at="[NOW]"/>

    <tenants id="201b7707-acc8-44d3-8275-4c3af41327eb"/>

    <users id="fb3721d1-2e03-40ab-adb5-87545335d232"
           login="testOwner"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           blocked="false"
           verified="true"
           language="EN"
           version="1"
           created_at="[NOW]"
           modified_at="[NOW]"
           active="true"/>

    <personal_data user_id="fb3721d1-2e03-40ab-adb5-87545335d232"
                   email="testOwner@abcd.com"
                   first_name="test"
                   last_name="test"/>

    <access_levels active="true"
                   version="1"
                   id="22f34716-3b77-4e63-809d-35f9a4758012"
                   user_id="fb3721d1-2e03-40ab-adb5-87545335d232"
                   level="OWNER"
                   created_at="[NOW]"
                   modified_at="[NOW]"/>

    <owners id="22f34716-3b77-4e63-809d-35f9a4758012"/>

    <tokens id="6bcef94d-16f5-401b-a8d0-9461257572f9"
            token="20099985"
            purpose="OTP"
            user_id="fb3721d1-2e03-40ab-adb5-87545335d232"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            expiration_date="2039-05-04 14:33:01.413581"
            version="0"
            created_by="[NULL]"
            modified_by="[NULL]"/>

    <users id="7499b44f-1054-42f7-9ac1-8256840acc2c"
           login="testAdmin"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           blocked="false"
           verified="true"
           language="EN"
           version="1"
           created_at="[NOW]"
           modified_at="[NOW]"
           active="true"/>

    <personal_data user_id="7499b44f-1054-42f7-9ac1-8256840acc2c"
                   email="testAdmin@abcd.com"
                   first_name="testadmin"
                   last_name="testadmin"/>

    <access_levels id="33a1a4f3-37ca-4db7-955e-990c92622d34"
                   user_id="7499b44f-1054-42f7-9ac1-8256840acc2c"
                   level="ADMINISTRATOR"
                   active="true"
                   version="1"
                   created_at="[NOW]"
                   modified_at="[NOW]"/>

    <administrators id="33a1a4f3-37ca-4db7-955e-990c92622d34"/>

    <tokens id="6bcef94d-16f5-401b-a0d0-9461257572f9"
            token="20099984"
            purpose="OTP"
            user_id="7499b44f-1054-42f7-9ac1-8256840acc2c"
            created_at="2024-05-04 14:33:01.413581"
            modified_at="2024-05-04 14:33:01.413581"
            expiration_date="2039-05-04 14:33:01.413581"
            version="0"
            created_by="[NULL]"
            modified_by="[NULL]"/>

    <role_requests id="b24db498-3048-4282-b33c-241b7cab81de"
                   version="1"
                   created_at="[NOW]"
                   modified_at="[NOW]"
                   request_date="[NOW]"
                   tenant_id="9163ede4-241f-4b54-ab1a-d1eb6cc728d8"/>

    <role_requests id="b24db498-3048-4282-b33c-241b7cab81df"
                   version="1"
                   created_at="[NOW]"
                   modified_at="[NOW]"
                   request_date="[NOW]"
                   tenant_id="201b7707-acc8-44d3-8275-4c3af41327eb"/>

</dataset>

=== KacperKafara/LandlordKingdom/src/test/resources/datasets/usersForUsersIT.xml
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="userSchema.xsd">

    <!-- Administrator -->
    <users id="ba537227-d54f-42b3-aa58-10492cddf8a6"
           login="adminUser"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           last_successful_login="2024-05-04 14:33:01.413581"
           last_failed_login="2024-05-04 14:33:01.413581"
           last_successful_login_ip="[NULL]"
           last_failed_login_ip="[NULL]"
           blocked="false"
           verified="true"
           language="EN"
           version="0"
           created_at="[NOW]"/>

    <!-- Personal Data -->
    <personal_data user_id="ba537227-d54f-42b3-aa58-10492cddf8a6"
                   email="adminUser@test.com"
                   first_name="AdminUser"
                   last_name="AdminUser"/>

    <!-- Access Level -->
    <access_levels active="true"
                   version="0"
                   id="22f34716-3b77-4e63-809d-35f9a4758011"
                   user_id="ba537227-d54f-42b3-aa58-10492cddf8a6"
                   level="ADMINISTRATOR"/>

    <!-- Administrator -->
    <administrators id="22f34716-3b77-4e63-809d-35f9a4758011"/>

    <!-- Unblocked and Verified User -->
    <users id="2d1c91e8-cc0c-4f33-ae6e-20a9948a6f2d"
           login="user"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           last_successful_login="2024-05-04 14:33:01.413581"
           last_failed_login="2024-05-04 14:33:01.413581"
           last_successful_login_ip="[NULL]"
           last_failed_login_ip="[NULL]"
           blocked="false"
           verified="true"
           language="EN"
           version="0"
           created_at="[NOW]"/>

    <!-- Personal Data -->
    <personal_data user_id="2d1c91e8-cc0c-4f33-ae6e-20a9948a6f2d"
                   email="user@test.com"
                   first_name="User"
                   last_name="User"/>

    <!-- Access Level -->
    <access_levels active="true"
                   version="0"
                   id="22f34716-3b77-4e63-809d-35f9a4758012"
                   user_id="2d1c91e8-cc0c-4f33-ae6e-20a9948a6f2d"
                   level="TENANT"/>

    <!-- Tenant -->
    <tenants id="22f34716-3b77-4e63-809d-35f9a4758012"/>

    <!-- Tenant (Blocked) -->
    <users id="3a9a32e2-0f9e-4edf-b1ed-0e01386d6e49"
           login="blockedUser"
           password="$2a$12$bOPVAvWOC2f9gJoF37IeE.N9Ij15GfWeVlvHzDPTOJk66NimJMJ4."
           login_attempts="0"
           last_successful_login="2024-05-04 14:33:01.413581"
           last_failed_login="2024-05-04 14:33:01.413581"
           last_successful_login_ip="[NULL]"
           last_failed_login_ip="[NULL]"
           blocked="true"
           verified="true"
           language="EN"
           version="0"
           created_at="[NOW]"/>

    <!-- Personal Data -->
    <personal_data user_id="3a9a32e2-0f9e-4edf-b1ed-0e01386d6e49"
                   email="blockedUser@test.com"
                   first_name="Blocked"
                   last_name="User"/>

    <!-- Access Level -->
    <access_levels active="true"
                   version="0"
                   id="22f34716-3b77-4e63-809d-35f9a4758013"
                   user_id="3a9a32e2-0f9e-4edf-b1ed-0e01386d6e49"
                   level="TENANT"/>

    <tenants id="22f34716-3b77-4e63-809d-35f9a4758013"/>
</dataset>
